# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "CI"
  lane :ci do
    # test
    gradle(
      task: "test"
    )

    # lint
    gradle(
      task: "lint"
    )

    # codecov
    gradle(
      task: "jacocoTestReport"
    )
  end

  desc "CD"
  lane :cd do
    # clean
    gradle(
      task: "clean"
    )

    # release
    gradle(
      task: "assemble",
      build_type: "Release"
    )

    # upload to store
    upload_to_play_store(
      json_key: 'api-5946200078214302311-435660-cc2f74dfcfeb.json',
      track: 'beta'
    )

  end
end
